//! TS-vs-Rust differential check for Phase A.
//!
//! Reads `packages/rust-cvr/agentic/parity/parity-fixture.json` (generated by
//! `agentic/parity/generate-fixture.mjs`) and asserts every value the Rust
//! implementation produces matches the captured TS output exactly.
//!
//! Run via `cargo test --lib parity_check` from `packages/rust-cvr`.

use crate::hash::{h32, h64, h128};
use crate::row_key::{RowID, row_id_hash, row_id_string_cached};
use crate::row_set_signature::{format_signature, parse_signature, signature_unit};
use serde_json::Value;

fn parse_u64(s: &str) -> u64 {
    s.parse().expect("invalid u64 in fixture")
}

fn make_row_id_from_json(v: &Value) -> RowID {
    let obj = v.as_object().expect("rowID entry must be an object");
    let schema = obj
        .get("schema")
        .and_then(Value::as_str)
        .expect("schema missing")
        .to_string();
    let table = obj
        .get("table")
        .and_then(Value::as_str)
        .expect("table missing")
        .to_string();
    let row_key = obj
        .get("rowKey")
        .and_then(Value::as_object)
        .expect("rowKey missing");
    RowID {
        schema,
        table,
        row_key: row_key.clone(),
    }
}

#[test]
fn parity_check() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/agentic/parity/parity-fixture.json"
    );
    let bytes = std::fs::read(path)
        .unwrap_or_else(|e| panic!("failed to read fixture file {}: {}", path, e));
    let fixture: Value = serde_json::from_slice(&bytes).expect("fixture is not valid JSON");

    // Hash parity
    for entry in fixture
        .get("hashes")
        .and_then(Value::as_array)
        .expect("fixture.hashes missing")
    {
        let input = entry
            .get("input")
            .and_then(Value::as_str)
            .expect("hash entry missing input");
        let expected_h32 = entry
            .get("h32")
            .and_then(Value::as_str)
            .expect("hash entry missing h32");
        let expected_h64 = entry
            .get("h64")
            .and_then(Value::as_str)
            .expect("hash entry missing h64");
        let expected_h128 = entry
            .get("h128")
            .and_then(Value::as_str)
            .expect("hash entry missing h128");

        assert_eq!(
            h32(input).to_string(),
            expected_h32,
            "h32 mismatch for input {:?}",
            input
        );
        assert_eq!(
            h64(input).to_string(),
            expected_h64,
            "h64 mismatch for input {:?}",
            input
        );
        assert_eq!(
            h128(input).to_string(),
            expected_h128,
            "h128 mismatch for input {:?}",
            input
        );
    }

    // RowID string/hash/signature parity
    for entry in fixture
        .get("rowIds")
        .and_then(Value::as_array)
        .expect("fixture.rowIds missing")
    {
        let input = entry.get("input").expect("rowId entry missing input");
        let expected_row_id_string = entry
            .get("rowIDString")
            .and_then(Value::as_str)
            .expect("rowId entry missing rowIDString");
        let expected_row_id_hash = entry
            .get("rowIDHash")
            .and_then(Value::as_str)
            .expect("rowId entry missing rowIDHash");
        let expected_signature = entry
            .get("rowIDSignatureUnit")
            .and_then(Value::as_str)
            .expect("rowId entry missing rowIDSignatureUnit");

        let id = make_row_id_from_json(input);
        let actual_row_id_string = row_id_string_cached(&id);
        let actual_row_id_hash = row_id_hash(&id);
        let actual_signature = signature_unit(&id).to_string();

        assert_eq!(
            actual_row_id_string, expected_row_id_string,
            "rowIDString mismatch for {:?}",
            input
        );
        assert_eq!(
            actual_row_id_hash, expected_row_id_hash,
            "rowIDHash mismatch for {:?}",
            input
        );
        assert_eq!(
            actual_signature, expected_signature,
            "rowIDSignatureUnit mismatch for {:?}",
            input
        );
    }

    // Signature format/parse round-trip parity
    for entry in fixture
        .get("signatures")
        .and_then(Value::as_array)
        .expect("fixture.signatures missing")
    {
        let expected_sig = entry
            .get("sig")
            .and_then(Value::as_str)
            .expect("signature entry missing sig");
        let expected_hex = entry
            .get("hex")
            .and_then(Value::as_str)
            .expect("signature entry missing hex");

        let sig = parse_u64(expected_sig);
        let hex = format_signature(sig);
        assert_eq!(
            hex, expected_hex,
            "formatSignature mismatch for sig {}",
            sig
        );

        let parsed = parse_signature(Some(&hex)).expect("parseSignature failed");
        assert_eq!(
            parsed.to_string(),
            expected_sig,
            "parseSignature mismatch for hex {}",
            hex
        );
    }
}
