//! TS-vs-Rust differential check.
//!
//! Reads `packages/rust-cvr/agentic/parity/parity-fixture.json` (generated by
//! `agentic/parity/generate-fixture.mjs` running the real TS implementations)
//! and asserts every value the Rust port produces matches the captured TS
//! output exactly. This pins the Rust code to TS's *actual* behavior rather
//! than the porter's interpretation of it.
//!
//! Coverage: primitives (hash / rowID / signature); the CVR version semantic
//! layer (lexi, versionString, versionFromString, cmpVersions — incl. the falsy
//! `configVersion == 0` contract); getInactiveQueries; mergeRefCounts;
//! queryRecordToQueryRow; and makeRowPatch (poke row serialization).
//!
//! Tier-A leaf gaps: TTL parse/clamp/compare (incl. forever/none); row_id_string
//! (uncached) and normalizedKeyOrder; and the version-helper family — oneAfter,
//! maxVersion, versionToCookie, versionToNullableCookie, cmp_cvr, and
//! try_version_from_string (which now validates the stateVersion in the 1-part
//! case, matching TS `versionFromString`).
//!
//! Run via `cargo test --lib parity_check` from `packages/rust-cvr`.

use crate::client_handler::make_row_patch;
use crate::cvr::{get_inactive_queries, merge_ref_counts};
use crate::hash::{h32, h64, h128};
use crate::row_key::{
    RowID, RowKey, normalized_key_order, row_id_hash, row_id_string, row_id_string_cached,
};
use crate::row_set_signature::{format_signature, parse_signature, signature_unit};
use crate::store::query_record_to_query_row;
use crate::ttl::{TTL, clamp_ttl, compare_ttl, parse_ttl, parse_ttl_string};
use crate::types::{
    BaseQueryRecord, CVR, ClientQueryRecord, ClientState, CustomQueryRecord, DesiredQuerySpec,
    InternalQueryRecord, Patch, PatchToVersion, QueryPatch, QueryRecord, RefCounts, RowPatch,
    RowRecord, RowUpdate, ShardID, StoreOp,
};
use crate::updater::{CVRConfigDrivenUpdater, CVRQueryDrivenUpdater};
use crate::version::{
    CVRVersion, NullableCVRVersion, cmp_cvr, cmp_versions, max_version, one_after,
    try_version_from_string, version_from_lexi, version_from_string, version_string,
    version_to_cookie, version_to_lexi, version_to_nullable_cookie,
};
use serde_json::Value;
use std::cmp::Ordering;
use std::collections::{BTreeMap, HashMap, HashSet};

/// A fixture TTL input is either a JSON number (ms) or a string like "5m".
fn ttl_from_json(v: &Value) -> TTL {
    if let Some(n) = v.as_i64() {
        TTL::Ms(n)
    } else if let Some(s) = v.as_str() {
        parse_ttl_string(s)
    } else {
        panic!("ttl input must be int or string: {:?}", v)
    }
}

// ---- Tier-B (updater state-transition) helpers ----

fn base_cvr() -> CVR {
    CVR {
        id: "cg-parity".to_string(),
        version: CVRVersion {
            state_version: "v1".to_string(),
            config_version: None,
        },
        last_active: 0,
        ttl_clock: 0,
        replica_version: Some("r1".to_string()),
        clients: BTreeMap::new(),
        queries: BTreeMap::new(),
        client_schema: None,
        profile_id: None,
    }
}

fn parity_shard() -> ShardID {
    ShardID {
        app_id: "test".to_string(),
        shard_num: 0,
    }
}

fn spec_from_json(v: &Value) -> DesiredQuerySpec {
    DesiredQuerySpec {
        hash: v
            .get("hash")
            .and_then(Value::as_str)
            .expect("hash")
            .to_string(),
        ast: v.get("ast").cloned(),
        name: v.get("name").and_then(Value::as_str).map(str::to_string),
        args: v.get("args").and_then(Value::as_array).cloned(),
        ttl: v.get("ttl").and_then(Value::as_i64),
    }
}

/// Canonical patch form matching the generator's `normPatch`.
fn norm_patch(pv: &PatchToVersion) -> Value {
    let to_version = version_string(&pv.to_version);
    match &pv.patch {
        Patch::Query(qp) => {
            let (op, id, client_id) = match qp {
                QueryPatch::Put { id, client_id } => ("put", id, client_id),
                QueryPatch::Del { id, client_id } => ("del", id, client_id),
            };
            serde_json::json!({
                "kind": "query", "op": op, "id": id,
                "clientID": client_id, "toVersion": to_version,
            })
        }
        Patch::Row(rp) => match rp {
            RowPatch::Put { id, contents } => serde_json::json!({
                "kind": "row", "op": "put",
                "id": serde_json::to_value(id).unwrap(),
                "contents": &**contents, "toVersion": to_version,
            }),
            RowPatch::Del { id } => serde_json::json!({
                "kind": "row", "op": "del",
                "id": serde_json::to_value(id).unwrap(), "toVersion": to_version,
            }),
        },
    }
}

/// Canonical putDesiredQuery StoreOp form matching the generator's stub capture.
fn norm_put_desired_op(op: &StoreOp) -> Option<Value> {
    match op {
        StoreOp::PutDesiredQuery {
            version,
            query_id,
            client_id,
            deleted,
            inactivated_at,
            ttl,
        } => Some(serde_json::json!({
            "op": "putDesiredQuery",
            "version": version_string(version),
            "queryID": query_id,
            "clientID": client_id,
            "deleted": deleted,
            "inactivatedAt": inactivated_at,
            "ttl": ttl,
        })),
        _ => None,
    }
}

/// Stable patch sort key matching the generator's `patchSortKey`.
fn patch_sort_key(pv: &PatchToVersion) -> String {
    match &pv.patch {
        Patch::Row(rp) => {
            let id = match rp {
                RowPatch::Put { id, .. } => id,
                RowPatch::Del { id } => id,
            };
            format!("row:{}", row_id_string(id))
        }
        Patch::Query(qp) => {
            let id = match qp {
                QueryPatch::Put { id, .. } => id,
                QueryPatch::Del { id, .. } => id,
            };
            format!("query:{id}")
        }
    }
}

/// Sort by the stable key (row patches come out of a HashMap on the Rust side),
/// then normalize — matching the generator, which sorts before `normPatch`.
fn sorted_norm(mut patches: Vec<PatchToVersion>) -> Value {
    patches.sort_by_key(patch_sort_key);
    Value::Array(patches.iter().map(norm_patch).collect())
}

fn client_query_record(hash: &str, q: &Value) -> QueryRecord {
    QueryRecord::Client(ClientQueryRecord {
        base: BaseQueryRecord {
            id: hash.to_string(),
            transformation_hash: q
                .get("transformationHash")
                .and_then(Value::as_str)
                .map(str::to_string),
            transformation_version: None,
            row_set_signature: None,
        },
        ast: q.get("ast").cloned().unwrap_or(Value::Null),
        client_state: BTreeMap::new(),
        patch_version: q
            .get("patchVersion")
            .filter(|v| !v.is_null())
            .map(|v| serde_json::from_value(v.clone()).expect("patchVersion")),
    })
}

/// Build the `received` rows map (keyed by rowIDString) from fixture specs.
fn build_received_rows(specs: &[Value]) -> HashMap<String, (RowID, RowUpdate)> {
    let mut rows = HashMap::new();
    for r in specs {
        let id = make_row_id_from_json(r.get("id").expect("row id"));
        let id_str = row_id_string(&id);
        let update = RowUpdate {
            version: r.get("version").and_then(Value::as_str).map(str::to_string),
            contents: r.get("contents").cloned().map(std::sync::Arc::new),
            ref_counts: parse_refcounts(r.get("refCounts").expect("refCounts")).unwrap_or_default(),
        };
        rows.insert(id_str, (id, update));
    }
    rows
}

/// Build the existing RowRecord map (keyed by rowIDString) from fixture specs.
fn build_existing_rows(specs: &[Value]) -> HashMap<String, RowRecord> {
    let mut m = HashMap::new();
    for e in specs {
        let id = make_row_id_from_json(e.get("id").expect("existing id"));
        let id_str = row_id_string(&id);
        m.insert(
            id_str,
            RowRecord {
                id,
                row_version: e
                    .get("rowVersion")
                    .and_then(Value::as_str)
                    .expect("rowVersion")
                    .to_string(),
                patch_version: serde_json::from_value(
                    e.get("patchVersion").expect("patchVersion").clone(),
                )
                .expect("patchVersion"),
                ref_counts: parse_refcounts(e.get("refCounts").expect("refCounts")),
            },
        );
    }
    m
}

/// Resulting desire state matching the generator's `normDesireState`.
fn norm_desire_state(cvr: &CVR) -> Value {
    let mut clients = serde_json::Map::new();
    for (cid, c) in &cvr.clients {
        let mut ids = c.desired_query_ids.clone();
        ids.sort();
        clients.insert(cid.clone(), serde_json::to_value(ids).unwrap());
    }
    let mut queries = serde_json::Map::new();
    for (qh, q) in &cvr.queries {
        let (ty, cs) = match q {
            QueryRecord::Internal(_) => continue,
            QueryRecord::Client(r) => ("client", &r.client_state),
            QueryRecord::Custom(r) => ("custom", &r.client_state),
        };
        let mut csm = serde_json::Map::new();
        for (cid, s) in cs {
            csm.insert(
                cid.clone(),
                serde_json::json!({"inactivatedAt": s.inactivated_at, "ttl": s.ttl}),
            );
        }
        queries.insert(
            qh.clone(),
            serde_json::json!({"type": ty, "clientState": Value::Object(csm)}),
        );
    }
    serde_json::json!({"clients": Value::Object(clients), "queries": Value::Object(queries)})
}

/// Parse a fixture RefCounts value (`{hash: count}` or `null`) into `Option`.
fn parse_refcounts(v: &Value) -> Option<RefCounts> {
    if v.is_null() {
        return None;
    }
    let mut m = RefCounts::new();
    for (k, val) in v.as_object().expect("refcounts must be object") {
        m.insert(k.clone(), val.as_i64().expect("refcount value must be int"));
    }
    Some(m)
}

fn parse_u64(s: &str) -> u64 {
    s.parse().expect("invalid u64 in fixture")
}

fn make_row_id_from_json(v: &Value) -> RowID {
    let obj = v.as_object().expect("rowID entry must be an object");
    let schema = obj
        .get("schema")
        .and_then(Value::as_str)
        .expect("schema missing")
        .to_string();
    let table = obj
        .get("table")
        .and_then(Value::as_str)
        .expect("table missing")
        .to_string();
    let row_key = obj
        .get("rowKey")
        .and_then(Value::as_object)
        .expect("rowKey missing");
    RowID {
        schema,
        table,
        row_key: row_key.clone(),
    }
}

/// Build a minimal CVR from the compact fixture spec used by the
/// `inactiveQueries` cases. Only the fields `get_inactive_queries` reads
/// (query type + per-client `inactivatedAt`/`ttl`) carry meaning; the rest are
/// dummies. `inactivatedAt` absent in the JSON => `None` (TS `undefined`).
fn build_client_state(cs: &serde_json::Map<String, Value>) -> BTreeMap<String, ClientState> {
    let mut m = BTreeMap::new();
    for (cid, s) in cs {
        let obj = s.as_object().expect("clientState entry must be object");
        m.insert(
            cid.clone(),
            ClientState {
                inactivated_at: obj.get("inactivatedAt").and_then(Value::as_i64),
                ttl: obj.get("ttl").and_then(Value::as_i64).expect("ttl"),
                version: CVRVersion::empty(),
            },
        );
    }
    m
}

fn dummy_base(id: &str) -> BaseQueryRecord {
    BaseQueryRecord {
        id: id.to_string(),
        transformation_hash: None,
        transformation_version: None,
        row_set_signature: None,
    }
}

fn build_cvr_from_spec(queries: &Value) -> CVR {
    let mut q = BTreeMap::new();
    for (hash, spec) in queries.as_object().expect("queries must be object") {
        let ty = spec
            .get("type")
            .and_then(Value::as_str)
            .expect("query type");
        let client_state = || {
            build_client_state(
                spec.get("clientState")
                    .and_then(Value::as_object)
                    .expect("clientState"),
            )
        };
        let record = match ty {
            "internal" => QueryRecord::Internal(InternalQueryRecord {
                base: dummy_base(hash),
                ast: Value::Null,
            }),
            "custom" => QueryRecord::Custom(CustomQueryRecord {
                base: dummy_base(hash),
                name: "n".to_string(),
                args: vec![],
                client_state: client_state(),
                patch_version: None,
            }),
            _ => QueryRecord::Client(ClientQueryRecord {
                base: dummy_base(hash),
                ast: Value::Null,
                client_state: client_state(),
                patch_version: None,
            }),
        };
        q.insert(hash.clone(), record);
    }
    CVR {
        id: "parity".to_string(),
        version: CVRVersion::empty(),
        last_active: 0,
        ttl_clock: 0,
        replica_version: None,
        clients: BTreeMap::new(),
        queries: q,
        client_schema: None,
        profile_id: None,
    }
}

/// Build a QueryRecord from the compact `queryRows` spec (mirrors the TS
/// `buildQR` in generate-fixture.mjs).
fn build_query_record_from_spec(spec: &Value) -> QueryRecord {
    let id = spec.get("id").and_then(Value::as_str).expect("id");
    let ver = |k: &str| -> Option<CVRVersion> {
        spec.get(k)
            .filter(|v| !v.is_null())
            .map(|v| serde_json::from_value(v.clone()).expect("bad CVRVersion in spec"))
    };
    let base = BaseQueryRecord {
        id: id.to_string(),
        transformation_hash: spec
            .get("transformationHash")
            .and_then(Value::as_str)
            .map(str::to_string),
        transformation_version: ver("transformationVersion"),
        row_set_signature: spec
            .get("rowSetSignature")
            .and_then(Value::as_str)
            .map(str::to_string),
    };
    match spec.get("type").and_then(Value::as_str).expect("type") {
        "internal" => QueryRecord::Internal(InternalQueryRecord {
            base,
            ast: spec.get("ast").cloned().unwrap_or(Value::Null),
        }),
        "custom" => QueryRecord::Custom(CustomQueryRecord {
            base,
            name: spec
                .get("name")
                .and_then(Value::as_str)
                .expect("name")
                .to_string(),
            args: spec
                .get("args")
                .and_then(Value::as_array)
                .cloned()
                .unwrap_or_default(),
            client_state: BTreeMap::new(),
            patch_version: ver("patchVersion"),
        }),
        _ => QueryRecord::Client(ClientQueryRecord {
            base,
            ast: spec.get("ast").cloned().unwrap_or(Value::Null),
            client_state: BTreeMap::new(),
            patch_version: ver("patchVersion"),
        }),
    }
}

/// Build a RowPatch from the compact `rowPatches` spec.
fn build_row_patch_from_spec(spec: &Value) -> RowPatch {
    let id = spec.get("id").and_then(Value::as_object).expect("id");
    let row_id = RowID {
        schema: id
            .get("schema")
            .and_then(Value::as_str)
            .unwrap()
            .to_string(),
        table: id.get("table").and_then(Value::as_str).unwrap().to_string(),
        row_key: id
            .get("rowKey")
            .and_then(Value::as_object)
            .expect("rowKey")
            .clone(),
    };
    match spec.get("op").and_then(Value::as_str).expect("op") {
        "put" => RowPatch::Put {
            id: row_id,
            contents: std::sync::Arc::new(spec.get("contents").cloned().unwrap_or(Value::Null)),
        },
        _ => RowPatch::Del { id: row_id },
    }
}

#[test]
fn parity_check() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/agentic/parity/parity-fixture.json"
    );
    let bytes = std::fs::read(path)
        .unwrap_or_else(|e| panic!("failed to read fixture file {}: {}", path, e));
    let fixture: Value = serde_json::from_slice(&bytes).expect("fixture is not valid JSON");

    // Hash parity
    for entry in fixture
        .get("hashes")
        .and_then(Value::as_array)
        .expect("fixture.hashes missing")
    {
        let input = entry
            .get("input")
            .and_then(Value::as_str)
            .expect("hash entry missing input");
        let expected_h32 = entry
            .get("h32")
            .and_then(Value::as_str)
            .expect("hash entry missing h32");
        let expected_h64 = entry
            .get("h64")
            .and_then(Value::as_str)
            .expect("hash entry missing h64");
        let expected_h128 = entry
            .get("h128")
            .and_then(Value::as_str)
            .expect("hash entry missing h128");

        assert_eq!(
            h32(input).to_string(),
            expected_h32,
            "h32 mismatch for input {:?}",
            input
        );
        assert_eq!(
            h64(input).to_string(),
            expected_h64,
            "h64 mismatch for input {:?}",
            input
        );
        assert_eq!(
            h128(input).to_string(),
            expected_h128,
            "h128 mismatch for input {:?}",
            input
        );
    }

    // RowID string/hash/signature parity
    for entry in fixture
        .get("rowIds")
        .and_then(Value::as_array)
        .expect("fixture.rowIds missing")
    {
        let input = entry.get("input").expect("rowId entry missing input");
        let expected_row_id_string = entry
            .get("rowIDString")
            .and_then(Value::as_str)
            .expect("rowId entry missing rowIDString");
        let expected_row_id_hash = entry
            .get("rowIDHash")
            .and_then(Value::as_str)
            .expect("rowId entry missing rowIDHash");
        let expected_signature = entry
            .get("rowIDSignatureUnit")
            .and_then(Value::as_str)
            .expect("rowId entry missing rowIDSignatureUnit");

        let id = make_row_id_from_json(input);
        let actual_row_id_string = row_id_string_cached(&id);
        let actual_row_id_hash = row_id_hash(&id);
        let actual_signature = signature_unit(&id).to_string();

        assert_eq!(
            actual_row_id_string, expected_row_id_string,
            "rowIDString mismatch for {:?}",
            input
        );
        // the uncached row_id_string must agree with the cached variant / TS
        assert_eq!(
            row_id_string(&id),
            expected_row_id_string,
            "row_id_string (uncached) mismatch for {:?}",
            input
        );
        assert_eq!(
            actual_row_id_hash, expected_row_id_hash,
            "rowIDHash mismatch for {:?}",
            input
        );
        assert_eq!(
            actual_signature, expected_signature,
            "rowIDSignatureUnit mismatch for {:?}",
            input
        );
    }

    // Signature format/parse round-trip parity
    for entry in fixture
        .get("signatures")
        .and_then(Value::as_array)
        .expect("fixture.signatures missing")
    {
        let expected_sig = entry
            .get("sig")
            .and_then(Value::as_str)
            .expect("signature entry missing sig");
        let expected_hex = entry
            .get("hex")
            .and_then(Value::as_str)
            .expect("signature entry missing hex");

        let sig = parse_u64(expected_sig);
        let hex = format_signature(sig);
        assert_eq!(
            hex, expected_hex,
            "formatSignature mismatch for sig {}",
            sig
        );

        let parsed = parse_signature(Some(&hex)).expect("parseSignature failed");
        assert_eq!(
            parsed.to_string(),
            expected_sig,
            "parseSignature mismatch for hex {}",
            hex
        );
    }

    // ---- ② semantic layer: CVR version encoding + comparison ----

    // LexiVersion round-trip parity (versionToLexi / versionFromLexi).
    for entry in fixture
        .get("lexiVersions")
        .and_then(Value::as_array)
        .expect("fixture.lexiVersions missing")
    {
        let value = entry.get("value").and_then(Value::as_str).expect("value");
        let expected_lexi = entry.get("lexi").and_then(Value::as_str).expect("lexi");
        let expected_round = entry
            .get("roundTrip")
            .and_then(Value::as_str)
            .expect("roundTrip");
        let n: u64 = value.parse().expect("lexi value not u64");
        assert_eq!(
            version_to_lexi(n),
            expected_lexi,
            "versionToLexi mismatch for {}",
            value
        );
        let round = version_from_lexi(expected_lexi).expect("versionFromLexi failed");
        assert_eq!(
            round.to_string(),
            expected_round,
            "versionFromLexi mismatch for {}",
            expected_lexi
        );
    }

    // CVRVersion -> versionString parity (incl. the falsy configVersion==0 case).
    for entry in fixture
        .get("cvrVersions")
        .and_then(Value::as_array)
        .expect("fixture.cvrVersions missing")
    {
        let input = entry.get("input").expect("cvrVersion input");
        let expected = entry
            .get("versionString")
            .and_then(Value::as_str)
            .expect("versionString");
        let v: CVRVersion =
            serde_json::from_value(input.clone()).expect("cvrVersion input not a CVRVersion");
        assert_eq!(
            version_string(&v),
            expected,
            "versionString mismatch for {:?}",
            input
        );
    }

    // Cookie -> versionFromString parity.
    for entry in fixture
        .get("cookies")
        .and_then(Value::as_array)
        .expect("fixture.cookies missing")
    {
        let cookie = entry.get("cookie").and_then(Value::as_str).expect("cookie");
        let expected: CVRVersion =
            serde_json::from_value(entry.get("version").expect("cookie version").clone())
                .expect("cookie version not a CVRVersion");
        assert_eq!(
            version_from_string(cookie),
            expected,
            "versionFromString mismatch for {:?}",
            cookie
        );
    }

    // cmpVersions ordering parity (nullable pairs + config tie-break).
    for entry in fixture
        .get("cmp")
        .and_then(Value::as_array)
        .expect("fixture.cmp missing")
    {
        let a: NullableCVRVersion =
            serde_json::from_value(entry.get("a").expect("cmp a").clone()).expect("cmp a");
        let b: NullableCVRVersion =
            serde_json::from_value(entry.get("b").expect("cmp b").clone()).expect("cmp b");
        let expected_sign = entry.get("sign").and_then(Value::as_i64).expect("cmp sign");
        let actual_sign = match cmp_versions(&a, &b) {
            Ordering::Less => -1,
            Ordering::Equal => 0,
            Ordering::Greater => 1,
        };
        assert_eq!(
            actual_sign, expected_sign,
            "cmpVersions mismatch for {:?} vs {:?}",
            a, b
        );
    }

    // getInactiveQueries accumulation + sort parity. Two checks:
    //  (1) the SET of (hash, inactivatedAt, ttl) must match — pins inclusion,
    //      the furthest-future max-per-query, clampTTL, and internal exclusion;
    //  (2) the eviction-time SEQUENCE (inactivatedAt + ttl) must match — pins
    //      sort order while tolerating the benign equal-eviction tie-break
    //      divergence (TS insertion-order vs Rust BTreeMap order), which every
    //      caller consumes order-independently. See get_inactive_queries docs.
    for entry in fixture
        .get("inactiveQueries")
        .and_then(Value::as_array)
        .expect("fixture.inactiveQueries missing")
    {
        let desc = entry.get("desc").and_then(Value::as_str).unwrap_or("");
        let queries = entry.get("queries").expect("inactiveQueries case queries");
        let expected = entry
            .get("expected")
            .and_then(Value::as_array)
            .expect("inactiveQueries case expected");

        let cvr = build_cvr_from_spec(queries);
        let actual = get_inactive_queries(&cvr);

        let exp_tuple = |e: &Value| {
            (
                e.get("hash").and_then(Value::as_str).unwrap().to_string(),
                e.get("inactivatedAt").and_then(Value::as_i64).unwrap(),
                e.get("ttl").and_then(Value::as_i64).unwrap(),
            )
        };
        let mut exp_set: Vec<_> = expected.iter().map(exp_tuple).collect();
        let mut act_set: Vec<_> = actual
            .iter()
            .map(|q| (q.hash.clone(), q.inactivated_at, q.ttl))
            .collect();
        exp_set.sort();
        act_set.sort();
        assert_eq!(
            act_set, exp_set,
            "getInactiveQueries set mismatch [{}]",
            desc
        );

        let exp_seq: Vec<i64> = expected
            .iter()
            .map(|e| {
                let t = exp_tuple(e);
                t.1 + t.2
            })
            .collect();
        let act_seq: Vec<i64> = actual.iter().map(|q| q.inactivated_at + q.ttl).collect();
        assert_eq!(
            act_seq, exp_seq,
            "getInactiveQueries eviction-order mismatch [{}]",
            desc
        );
    }

    // makeRowPatch parity — RowPatch -> rowsPatch wire op (the poke
    // serialization). Pins put value passthrough and del id shape, incl. the
    // poisoned-rowKey passthrough. NOTE: TS also runs ensureSafeJSON (throws on
    // bigints > 2^53); that edge is not representable in JSON/serde_json and is
    // tracked separately as a known gap, not asserted here.
    for entry in fixture
        .get("rowPatches")
        .and_then(Value::as_array)
        .expect("fixture.rowPatches missing")
    {
        let desc = entry.get("desc").and_then(Value::as_str).unwrap_or("");
        let spec = entry.get("patch").expect("rowPatch patch");
        let expected = entry.get("expected").expect("rowPatch expected");
        let op = make_row_patch(&build_row_patch_from_spec(spec)).expect("make_row_patch");
        let actual = serde_json::to_value(&op).unwrap();
        assert_eq!(&actual, expected, "makeRowPatch mismatch [{}]", desc);
    }

    // queryRecordToQueryRow parity — QueryRecord -> QueriesRow field mapping
    // (internal=true vs null, clientAST null for custom, queryArgs passthrough,
    // patchVersion via maybeVersionString incl. the falsy configVersion==0 case).
    for entry in fixture
        .get("queryRows")
        .and_then(Value::as_array)
        .expect("fixture.queryRows missing")
    {
        let desc = entry.get("desc").and_then(Value::as_str).unwrap_or("");
        let spec = entry.get("spec").expect("queryRow spec");
        let expected = entry.get("expected").expect("queryRow expected");
        let qr = build_query_record_from_spec(spec);
        let row = query_record_to_query_row("cg-parity", &qr);
        let actual = serde_json::json!({
            "clientGroupID": row.client_group_id,
            "queryHash": row.query_hash,
            "clientAST": row.client_ast,
            "queryName": row.query_name,
            "queryArgs": row.query_args,
            "patchVersion": row.patch_version,
            "transformationHash": row.transformation_hash,
            "transformationVersion": row.transformation_version,
            "internal": row.internal,
            "deleted": row.deleted,
            "rowSetSignature": row.row_set_signature,
        });
        assert_eq!(
            &actual, expected,
            "queryRecordToQueryRow mismatch [{}]",
            desc
        );
    }

    // mergeRefCounts parity — pins the no-existing zero-retention, negative
    // cancellation, all-zero -> null, and removeHashes-on-existing rules.
    for entry in fixture
        .get("refCountMerges")
        .and_then(Value::as_array)
        .expect("fixture.refCountMerges missing")
    {
        let existing = parse_refcounts(entry.get("existing").expect("existing"));
        let received = parse_refcounts(entry.get("received").expect("received"));
        let remove: Option<HashSet<String>> = entry
            .get("removeHashes")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .map(|s| s.as_str().expect("hash str").to_string())
                    .collect()
            });
        let expected = parse_refcounts(entry.get("expected").expect("expected"));
        let actual = merge_ref_counts(existing.as_ref(), received.as_ref(), remove.as_ref());
        assert_eq!(
            actual, expected,
            "mergeRefCounts mismatch existing={:?} received={:?} rm={:?}",
            existing, received, remove
        );
    }

    // ---- ③ Tier-A leaf gaps ----

    // TTL: parseTTL / clampTTL over numbers + string forms (incl. forever/none).
    for entry in fixture
        .get("ttls")
        .and_then(Value::as_array)
        .expect("fixture.ttls missing")
    {
        let input = entry.get("input").expect("ttl input");
        let expected_parse = entry.get("parse").and_then(Value::as_i64).expect("parse");
        let expected_clamp = entry.get("clamp").and_then(Value::as_i64).expect("clamp");
        let ttl = ttl_from_json(input);
        assert_eq!(
            parse_ttl(ttl),
            expected_parse,
            "parseTTL mismatch for {:?}",
            input
        );
        assert_eq!(
            clamp_ttl(ttl),
            expected_clamp,
            "clampTTL mismatch for {:?}",
            input
        );
    }

    // compareTTL: forever-aware ordering (exact difference, not just sign).
    for entry in fixture
        .get("ttlCompares")
        .and_then(Value::as_array)
        .expect("fixture.ttlCompares missing")
    {
        let a = ttl_from_json(entry.get("a").expect("a"));
        let b = ttl_from_json(entry.get("b").expect("b"));
        let expected = entry.get("cmp").and_then(Value::as_i64).expect("cmp");
        assert_eq!(
            compare_ttl(a, b),
            expected,
            "compareTTL mismatch a={:?} b={:?}",
            entry.get("a"),
            entry.get("b")
        );
    }

    // normalizedKeyOrder: single-col, ordered, and out-of-order (sort branch).
    for entry in fixture
        .get("normalizedKeys")
        .and_then(Value::as_array)
        .expect("fixture.normalizedKeys missing")
    {
        let input = entry
            .get("input")
            .and_then(Value::as_object)
            .expect("input obj");
        let expected = entry.get("order").expect("order");
        let key: RowKey = input.clone();
        let ordered = normalized_key_order(&key);
        let actual = Value::Array(
            ordered
                .iter()
                .map(|(k, v)| Value::Array(vec![Value::String((*k).clone()), (*v).clone()]))
                .collect(),
        );
        assert_eq!(
            &actual, expected,
            "normalizedKeyOrder mismatch for {:?}",
            input
        );
    }

    // oneAfter: NullableCVRVersion -> CVRVersion (compared via versionString).
    for entry in fixture
        .get("oneAfter")
        .and_then(Value::as_array)
        .expect("fixture.oneAfter missing")
    {
        let nv: NullableCVRVersion =
            serde_json::from_value(entry.get("input").expect("input").clone())
                .expect("nullable ver");
        let expected = entry
            .get("versionString")
            .and_then(Value::as_str)
            .expect("versionString");
        assert_eq!(
            version_string(&one_after(&nv)),
            expected,
            "oneAfter mismatch for {:?}",
            entry.get("input")
        );
    }

    // maxVersion: (CVRVersion, Option<CVRVersion>) -> CVRVersion.
    for entry in fixture
        .get("maxVersions")
        .and_then(Value::as_array)
        .expect("fixture.maxVersions missing")
    {
        let a: CVRVersion = serde_json::from_value(entry.get("a").expect("a").clone()).expect("a");
        let b_val = entry.get("b").expect("b");
        let b: Option<CVRVersion> = if b_val.is_null() {
            None
        } else {
            Some(serde_json::from_value(b_val.clone()).expect("b"))
        };
        let expected = entry
            .get("versionString")
            .and_then(Value::as_str)
            .expect("versionString");
        assert_eq!(
            version_string(&max_version(a, b)),
            expected,
            "maxVersion mismatch"
        );
    }

    // versionToCookie / versionToNullableCookie.
    for entry in fixture
        .get("versionCookies")
        .and_then(Value::as_array)
        .expect("fixture.versionCookies missing")
    {
        let v: CVRVersion =
            serde_json::from_value(entry.get("input").expect("input").clone()).expect("cvrversion");
        let expected = entry.get("cookie").and_then(Value::as_str).expect("cookie");
        assert_eq!(version_to_cookie(&v), expected, "versionToCookie mismatch");
    }
    for entry in fixture
        .get("nullableVersionCookies")
        .and_then(Value::as_array)
        .expect("fixture.nullableVersionCookies missing")
    {
        let nv: NullableCVRVersion =
            serde_json::from_value(entry.get("input").expect("input").clone()).expect("nullable");
        let cookie_val = entry.get("cookie").expect("cookie");
        let expected: Option<String> = if cookie_val.is_null() {
            None
        } else {
            Some(cookie_val.as_str().expect("cookie str").to_string())
        };
        assert_eq!(
            version_to_nullable_cookie(&nv),
            expected,
            "versionToNullableCookie mismatch"
        );
    }

    // cmp_cvr: non-null CVRVersion ordering (state + config tie-break).
    for entry in fixture
        .get("cmpCvr")
        .and_then(Value::as_array)
        .expect("fixture.cmpCvr missing")
    {
        let a: CVRVersion = serde_json::from_value(entry.get("a").expect("a").clone()).expect("a");
        let b: CVRVersion = serde_json::from_value(entry.get("b").expect("b").clone()).expect("b");
        let expected = entry.get("sign").and_then(Value::as_i64).expect("sign");
        let actual = match cmp_cvr(&a, &b) {
            Ordering::Less => -1,
            Ordering::Equal => 0,
            Ordering::Greater => 1,
        };
        assert_eq!(actual, expected, "cmpCvr mismatch {:?} vs {:?}", a, b);
    }

    // try_version_from_string: valid cookies parse; malformed strings (TS throws)
    // must return Err, not a bogus version.
    for entry in fixture
        .get("versionParses")
        .and_then(Value::as_array)
        .expect("fixture.versionParses missing")
    {
        let s = entry.get("str").and_then(Value::as_str).expect("str");
        let valid = entry.get("valid").and_then(Value::as_bool).expect("valid");
        match try_version_from_string(s) {
            Ok(v) => {
                assert!(valid, "try_version_from_string parsed {:?} but TS threw", s);
                let expected = entry
                    .get("versionString")
                    .and_then(Value::as_str)
                    .expect("versionString");
                assert_eq!(
                    version_string(&v),
                    expected,
                    "try_version_from_string mismatch for {:?}",
                    s
                );
            }
            Err(_) => assert!(
                !valid,
                "try_version_from_string errored on {:?} but TS accepted",
                s
            ),
        }
    }

    // ---- ④ Tier-B: CVRConfigDrivenUpdater.putDesiredQueries state transitions ----
    // Replay each scenario through the Rust updater and assert the returned
    // patches, the putDesiredQuery StoreOps, and the resulting desire state all
    // match what the real TS updater produced.
    for entry in fixture
        .get("configScenarios")
        .and_then(Value::as_array)
        .expect("fixture.configScenarios missing")
    {
        let desc = entry.get("desc").and_then(Value::as_str).unwrap_or("");
        let mut updater = CVRConfigDrivenUpdater::new(base_cvr(), parity_shard());

        let calls = entry.get("calls").and_then(Value::as_array).expect("calls");
        let call_results = entry
            .get("callResults")
            .and_then(Value::as_array)
            .expect("callResults");
        for (i, call) in calls.iter().enumerate() {
            let client_id = call
                .get("clientID")
                .and_then(Value::as_str)
                .expect("clientID");
            let specs: Vec<DesiredQuerySpec> = call
                .get("queries")
                .and_then(Value::as_array)
                .expect("queries")
                .iter()
                .map(spec_from_json)
                .collect();
            let patches = updater.put_desired_queries(client_id, &specs);
            let actual = Value::Array(patches.iter().map(norm_patch).collect());
            let expected = call_results[i].get("patches").expect("patches");
            assert_eq!(
                &actual, expected,
                "putDesiredQueries patches mismatch [{}] call {}",
                desc, i
            );
        }

        let ops = updater.base.drain_store_ops();
        let actual_ops = Value::Array(ops.iter().filter_map(norm_put_desired_op).collect());
        assert_eq!(
            &actual_ops,
            entry.get("desiredOps").expect("desiredOps"),
            "putDesiredQuery StoreOps mismatch [{}]",
            desc
        );

        assert_eq!(
            &norm_desire_state(&updater.base.cvr),
            entry.get("finalState").expect("finalState"),
            "final desire state mismatch [{}]",
            desc
        );
        assert_eq!(
            version_string(&updater.base.cvr.version),
            entry
                .get("finalVersion")
                .and_then(Value::as_str)
                .expect("finalVersion"),
            "final version mismatch [{}]",
            desc
        );
    }

    // ---- ⑤ Tier-B: CVRQueryDrivenUpdater trackQueries -> received -> deleteUnreferencedRows ----
    for entry in fixture
        .get("queryScenarios")
        .and_then(Value::as_array)
        .expect("fixture.queryScenarios missing")
    {
        let desc = entry.get("desc").and_then(Value::as_str).unwrap_or("");
        let state_version = entry
            .get("stateVersion")
            .and_then(Value::as_str)
            .expect("stateVersion");

        let mut cvr = base_cvr();
        for (h, q) in entry
            .get("queries")
            .and_then(Value::as_object)
            .expect("queries")
        {
            cvr.queries.insert(h.clone(), client_query_record(h, q));
        }

        let mut updater =
            CVRQueryDrivenUpdater::new(cvr, state_version.to_string(), "r1".to_string(), None);

        // trackQueries
        let exec_owned: Vec<(String, String)> = entry
            .get("executed")
            .and_then(Value::as_array)
            .expect("executed")
            .iter()
            .map(|e| {
                (
                    e.get("id").and_then(Value::as_str).expect("id").to_string(),
                    e.get("transformationHash")
                        .and_then(Value::as_str)
                        .expect("transformationHash")
                        .to_string(),
                )
            })
            .collect();
        let executed: Vec<(&str, &str)> = exec_owned
            .iter()
            .map(|(a, b)| (a.as_str(), b.as_str()))
            .collect();
        let removed_owned: Vec<String> = entry
            .get("removed")
            .and_then(Value::as_array)
            .expect("removed")
            .iter()
            .map(|r| r.get("id").and_then(Value::as_str).expect("id").to_string())
            .collect();
        let removed: Vec<&str> = removed_owned.iter().map(String::as_str).collect();

        let (_v, track_patches) = updater.track_queries(&executed, &removed);
        assert_eq!(
            &sorted_norm(track_patches),
            entry.get("trackPatches").expect("trackPatches"),
            "trackQueries patches mismatch [{}]",
            desc
        );

        // received
        let existing = build_existing_rows(
            entry
                .get("existingRows")
                .and_then(Value::as_array)
                .expect("existingRows"),
        );
        let rows = build_received_rows(
            entry
                .get("receivedRows")
                .and_then(Value::as_array)
                .expect("receivedRows"),
        );
        let recv_patches = updater.received(&rows, &existing);
        assert_eq!(
            &sorted_norm(recv_patches),
            entry.get("receivedPatches").expect("receivedPatches"),
            "received patches mismatch [{}]",
            desc
        );

        // deleteUnreferencedRows
        let del_patches = updater.delete_unreferenced_rows(existing.values());
        assert_eq!(
            &sorted_norm(del_patches),
            entry.get("deletePatches").expect("deletePatches"),
            "deleteUnreferencedRows patches mismatch [{}]",
            desc
        );

        assert_eq!(
            version_string(&updater.base.cvr.version),
            entry
                .get("finalVersion")
                .and_then(Value::as_str)
                .expect("finalVersion"),
            "query-driven final version mismatch [{}]",
            desc
        );
    }
}
