//! TS-vs-Rust differential check.
//!
//! Reads `packages/rust-cvr/agentic/parity/parity-fixture.json` (generated by
//! `agentic/parity/generate-fixture.mjs` running the real TS implementations)
//! and asserts every value the Rust port produces matches the captured TS
//! output exactly. This pins the Rust code to TS's *actual* behavior rather
//! than the porter's interpretation of it.
//!
//! Coverage: primitives (hash / rowID / signature); the CVR version semantic
//! layer (lexi, versionString, versionFromString, cmpVersions — incl. the falsy
//! `configVersion == 0` contract); getInactiveQueries; mergeRefCounts;
//! queryRecordToQueryRow; and makeRowPatch (poke row serialization).
//!
//! Run via `cargo test --lib parity_check` from `packages/rust-cvr`.

use crate::client_handler::make_row_patch;
use crate::cvr::{get_inactive_queries, merge_ref_counts};
use crate::hash::{h32, h64, h128};
use crate::row_key::{RowID, row_id_hash, row_id_string_cached};
use crate::row_set_signature::{format_signature, parse_signature, signature_unit};
use crate::store::query_record_to_query_row;
use crate::types::{
    BaseQueryRecord, CVR, ClientQueryRecord, ClientState, CustomQueryRecord, InternalQueryRecord,
    QueryRecord, RefCounts, RowPatch,
};
use crate::version::{
    CVRVersion, NullableCVRVersion, cmp_versions, version_from_lexi, version_from_string,
    version_string, version_to_lexi,
};
use serde_json::Value;
use std::cmp::Ordering;
use std::collections::{BTreeMap, HashSet};

/// Parse a fixture RefCounts value (`{hash: count}` or `null`) into `Option`.
fn parse_refcounts(v: &Value) -> Option<RefCounts> {
    if v.is_null() {
        return None;
    }
    let mut m = RefCounts::new();
    for (k, val) in v.as_object().expect("refcounts must be object") {
        m.insert(k.clone(), val.as_i64().expect("refcount value must be int"));
    }
    Some(m)
}

fn parse_u64(s: &str) -> u64 {
    s.parse().expect("invalid u64 in fixture")
}

fn make_row_id_from_json(v: &Value) -> RowID {
    let obj = v.as_object().expect("rowID entry must be an object");
    let schema = obj
        .get("schema")
        .and_then(Value::as_str)
        .expect("schema missing")
        .to_string();
    let table = obj
        .get("table")
        .and_then(Value::as_str)
        .expect("table missing")
        .to_string();
    let row_key = obj
        .get("rowKey")
        .and_then(Value::as_object)
        .expect("rowKey missing");
    RowID {
        schema,
        table,
        row_key: row_key.clone(),
    }
}

/// Build a minimal CVR from the compact fixture spec used by the
/// `inactiveQueries` cases. Only the fields `get_inactive_queries` reads
/// (query type + per-client `inactivatedAt`/`ttl`) carry meaning; the rest are
/// dummies. `inactivatedAt` absent in the JSON => `None` (TS `undefined`).
fn build_client_state(cs: &serde_json::Map<String, Value>) -> BTreeMap<String, ClientState> {
    let mut m = BTreeMap::new();
    for (cid, s) in cs {
        let obj = s.as_object().expect("clientState entry must be object");
        m.insert(
            cid.clone(),
            ClientState {
                inactivated_at: obj.get("inactivatedAt").and_then(Value::as_i64),
                ttl: obj.get("ttl").and_then(Value::as_i64).expect("ttl"),
                version: CVRVersion::empty(),
            },
        );
    }
    m
}

fn dummy_base(id: &str) -> BaseQueryRecord {
    BaseQueryRecord {
        id: id.to_string(),
        transformation_hash: None,
        transformation_version: None,
        row_set_signature: None,
    }
}

fn build_cvr_from_spec(queries: &Value) -> CVR {
    let mut q = BTreeMap::new();
    for (hash, spec) in queries.as_object().expect("queries must be object") {
        let ty = spec
            .get("type")
            .and_then(Value::as_str)
            .expect("query type");
        let client_state = || {
            build_client_state(
                spec.get("clientState")
                    .and_then(Value::as_object)
                    .expect("clientState"),
            )
        };
        let record = match ty {
            "internal" => QueryRecord::Internal(InternalQueryRecord {
                base: dummy_base(hash),
                ast: Value::Null,
            }),
            "custom" => QueryRecord::Custom(CustomQueryRecord {
                base: dummy_base(hash),
                name: "n".to_string(),
                args: vec![],
                client_state: client_state(),
                patch_version: None,
            }),
            _ => QueryRecord::Client(ClientQueryRecord {
                base: dummy_base(hash),
                ast: Value::Null,
                client_state: client_state(),
                patch_version: None,
            }),
        };
        q.insert(hash.clone(), record);
    }
    CVR {
        id: "parity".to_string(),
        version: CVRVersion::empty(),
        last_active: 0,
        ttl_clock: 0,
        replica_version: None,
        clients: BTreeMap::new(),
        queries: q,
        client_schema: None,
        profile_id: None,
    }
}

/// Build a QueryRecord from the compact `queryRows` spec (mirrors the TS
/// `buildQR` in generate-fixture.mjs).
fn build_query_record_from_spec(spec: &Value) -> QueryRecord {
    let id = spec.get("id").and_then(Value::as_str).expect("id");
    let ver = |k: &str| -> Option<CVRVersion> {
        spec.get(k)
            .filter(|v| !v.is_null())
            .map(|v| serde_json::from_value(v.clone()).expect("bad CVRVersion in spec"))
    };
    let base = BaseQueryRecord {
        id: id.to_string(),
        transformation_hash: spec
            .get("transformationHash")
            .and_then(Value::as_str)
            .map(str::to_string),
        transformation_version: ver("transformationVersion"),
        row_set_signature: spec
            .get("rowSetSignature")
            .and_then(Value::as_str)
            .map(str::to_string),
    };
    match spec.get("type").and_then(Value::as_str).expect("type") {
        "internal" => QueryRecord::Internal(InternalQueryRecord {
            base,
            ast: spec.get("ast").cloned().unwrap_or(Value::Null),
        }),
        "custom" => QueryRecord::Custom(CustomQueryRecord {
            base,
            name: spec
                .get("name")
                .and_then(Value::as_str)
                .expect("name")
                .to_string(),
            args: spec
                .get("args")
                .and_then(Value::as_array)
                .cloned()
                .unwrap_or_default(),
            client_state: BTreeMap::new(),
            patch_version: ver("patchVersion"),
        }),
        _ => QueryRecord::Client(ClientQueryRecord {
            base,
            ast: spec.get("ast").cloned().unwrap_or(Value::Null),
            client_state: BTreeMap::new(),
            patch_version: ver("patchVersion"),
        }),
    }
}

/// Build a RowPatch from the compact `rowPatches` spec.
fn build_row_patch_from_spec(spec: &Value) -> RowPatch {
    let id = spec.get("id").and_then(Value::as_object).expect("id");
    let row_id = RowID {
        schema: id
            .get("schema")
            .and_then(Value::as_str)
            .unwrap()
            .to_string(),
        table: id.get("table").and_then(Value::as_str).unwrap().to_string(),
        row_key: id
            .get("rowKey")
            .and_then(Value::as_object)
            .expect("rowKey")
            .clone(),
    };
    match spec.get("op").and_then(Value::as_str).expect("op") {
        "put" => RowPatch::Put {
            id: row_id,
            contents: spec.get("contents").cloned().unwrap_or(Value::Null),
        },
        _ => RowPatch::Del { id: row_id },
    }
}

#[test]
fn parity_check() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/agentic/parity/parity-fixture.json"
    );
    let bytes = std::fs::read(path)
        .unwrap_or_else(|e| panic!("failed to read fixture file {}: {}", path, e));
    let fixture: Value = serde_json::from_slice(&bytes).expect("fixture is not valid JSON");

    // Hash parity
    for entry in fixture
        .get("hashes")
        .and_then(Value::as_array)
        .expect("fixture.hashes missing")
    {
        let input = entry
            .get("input")
            .and_then(Value::as_str)
            .expect("hash entry missing input");
        let expected_h32 = entry
            .get("h32")
            .and_then(Value::as_str)
            .expect("hash entry missing h32");
        let expected_h64 = entry
            .get("h64")
            .and_then(Value::as_str)
            .expect("hash entry missing h64");
        let expected_h128 = entry
            .get("h128")
            .and_then(Value::as_str)
            .expect("hash entry missing h128");

        assert_eq!(
            h32(input).to_string(),
            expected_h32,
            "h32 mismatch for input {:?}",
            input
        );
        assert_eq!(
            h64(input).to_string(),
            expected_h64,
            "h64 mismatch for input {:?}",
            input
        );
        assert_eq!(
            h128(input).to_string(),
            expected_h128,
            "h128 mismatch for input {:?}",
            input
        );
    }

    // RowID string/hash/signature parity
    for entry in fixture
        .get("rowIds")
        .and_then(Value::as_array)
        .expect("fixture.rowIds missing")
    {
        let input = entry.get("input").expect("rowId entry missing input");
        let expected_row_id_string = entry
            .get("rowIDString")
            .and_then(Value::as_str)
            .expect("rowId entry missing rowIDString");
        let expected_row_id_hash = entry
            .get("rowIDHash")
            .and_then(Value::as_str)
            .expect("rowId entry missing rowIDHash");
        let expected_signature = entry
            .get("rowIDSignatureUnit")
            .and_then(Value::as_str)
            .expect("rowId entry missing rowIDSignatureUnit");

        let id = make_row_id_from_json(input);
        let actual_row_id_string = row_id_string_cached(&id);
        let actual_row_id_hash = row_id_hash(&id);
        let actual_signature = signature_unit(&id).to_string();

        assert_eq!(
            actual_row_id_string, expected_row_id_string,
            "rowIDString mismatch for {:?}",
            input
        );
        assert_eq!(
            actual_row_id_hash, expected_row_id_hash,
            "rowIDHash mismatch for {:?}",
            input
        );
        assert_eq!(
            actual_signature, expected_signature,
            "rowIDSignatureUnit mismatch for {:?}",
            input
        );
    }

    // Signature format/parse round-trip parity
    for entry in fixture
        .get("signatures")
        .and_then(Value::as_array)
        .expect("fixture.signatures missing")
    {
        let expected_sig = entry
            .get("sig")
            .and_then(Value::as_str)
            .expect("signature entry missing sig");
        let expected_hex = entry
            .get("hex")
            .and_then(Value::as_str)
            .expect("signature entry missing hex");

        let sig = parse_u64(expected_sig);
        let hex = format_signature(sig);
        assert_eq!(
            hex, expected_hex,
            "formatSignature mismatch for sig {}",
            sig
        );

        let parsed = parse_signature(Some(&hex)).expect("parseSignature failed");
        assert_eq!(
            parsed.to_string(),
            expected_sig,
            "parseSignature mismatch for hex {}",
            hex
        );
    }

    // ---- ② semantic layer: CVR version encoding + comparison ----

    // LexiVersion round-trip parity (versionToLexi / versionFromLexi).
    for entry in fixture
        .get("lexiVersions")
        .and_then(Value::as_array)
        .expect("fixture.lexiVersions missing")
    {
        let value = entry.get("value").and_then(Value::as_str).expect("value");
        let expected_lexi = entry.get("lexi").and_then(Value::as_str).expect("lexi");
        let expected_round = entry
            .get("roundTrip")
            .and_then(Value::as_str)
            .expect("roundTrip");
        let n: u64 = value.parse().expect("lexi value not u64");
        assert_eq!(
            version_to_lexi(n),
            expected_lexi,
            "versionToLexi mismatch for {}",
            value
        );
        let round = version_from_lexi(expected_lexi).expect("versionFromLexi failed");
        assert_eq!(
            round.to_string(),
            expected_round,
            "versionFromLexi mismatch for {}",
            expected_lexi
        );
    }

    // CVRVersion -> versionString parity (incl. the falsy configVersion==0 case).
    for entry in fixture
        .get("cvrVersions")
        .and_then(Value::as_array)
        .expect("fixture.cvrVersions missing")
    {
        let input = entry.get("input").expect("cvrVersion input");
        let expected = entry
            .get("versionString")
            .and_then(Value::as_str)
            .expect("versionString");
        let v: CVRVersion =
            serde_json::from_value(input.clone()).expect("cvrVersion input not a CVRVersion");
        assert_eq!(
            version_string(&v),
            expected,
            "versionString mismatch for {:?}",
            input
        );
    }

    // Cookie -> versionFromString parity.
    for entry in fixture
        .get("cookies")
        .and_then(Value::as_array)
        .expect("fixture.cookies missing")
    {
        let cookie = entry.get("cookie").and_then(Value::as_str).expect("cookie");
        let expected: CVRVersion =
            serde_json::from_value(entry.get("version").expect("cookie version").clone())
                .expect("cookie version not a CVRVersion");
        assert_eq!(
            version_from_string(cookie),
            expected,
            "versionFromString mismatch for {:?}",
            cookie
        );
    }

    // cmpVersions ordering parity (nullable pairs + config tie-break).
    for entry in fixture
        .get("cmp")
        .and_then(Value::as_array)
        .expect("fixture.cmp missing")
    {
        let a: NullableCVRVersion =
            serde_json::from_value(entry.get("a").expect("cmp a").clone()).expect("cmp a");
        let b: NullableCVRVersion =
            serde_json::from_value(entry.get("b").expect("cmp b").clone()).expect("cmp b");
        let expected_sign = entry.get("sign").and_then(Value::as_i64).expect("cmp sign");
        let actual_sign = match cmp_versions(&a, &b) {
            Ordering::Less => -1,
            Ordering::Equal => 0,
            Ordering::Greater => 1,
        };
        assert_eq!(
            actual_sign, expected_sign,
            "cmpVersions mismatch for {:?} vs {:?}",
            a, b
        );
    }

    // getInactiveQueries accumulation + sort parity. Two checks:
    //  (1) the SET of (hash, inactivatedAt, ttl) must match — pins inclusion,
    //      the furthest-future max-per-query, clampTTL, and internal exclusion;
    //  (2) the eviction-time SEQUENCE (inactivatedAt + ttl) must match — pins
    //      sort order while tolerating the benign equal-eviction tie-break
    //      divergence (TS insertion-order vs Rust BTreeMap order), which every
    //      caller consumes order-independently. See get_inactive_queries docs.
    for entry in fixture
        .get("inactiveQueries")
        .and_then(Value::as_array)
        .expect("fixture.inactiveQueries missing")
    {
        let desc = entry.get("desc").and_then(Value::as_str).unwrap_or("");
        let queries = entry.get("queries").expect("inactiveQueries case queries");
        let expected = entry
            .get("expected")
            .and_then(Value::as_array)
            .expect("inactiveQueries case expected");

        let cvr = build_cvr_from_spec(queries);
        let actual = get_inactive_queries(&cvr);

        let exp_tuple = |e: &Value| {
            (
                e.get("hash").and_then(Value::as_str).unwrap().to_string(),
                e.get("inactivatedAt").and_then(Value::as_i64).unwrap(),
                e.get("ttl").and_then(Value::as_i64).unwrap(),
            )
        };
        let mut exp_set: Vec<_> = expected.iter().map(exp_tuple).collect();
        let mut act_set: Vec<_> = actual
            .iter()
            .map(|q| (q.hash.clone(), q.inactivated_at, q.ttl))
            .collect();
        exp_set.sort();
        act_set.sort();
        assert_eq!(
            act_set, exp_set,
            "getInactiveQueries set mismatch [{}]",
            desc
        );

        let exp_seq: Vec<i64> = expected
            .iter()
            .map(|e| {
                let t = exp_tuple(e);
                t.1 + t.2
            })
            .collect();
        let act_seq: Vec<i64> = actual.iter().map(|q| q.inactivated_at + q.ttl).collect();
        assert_eq!(
            act_seq, exp_seq,
            "getInactiveQueries eviction-order mismatch [{}]",
            desc
        );
    }

    // makeRowPatch parity — RowPatch -> rowsPatch wire op (the poke
    // serialization). Pins put value passthrough and del id shape, incl. the
    // poisoned-rowKey passthrough. NOTE: TS also runs ensureSafeJSON (throws on
    // bigints > 2^53); that edge is not representable in JSON/serde_json and is
    // tracked separately as a known gap, not asserted here.
    for entry in fixture
        .get("rowPatches")
        .and_then(Value::as_array)
        .expect("fixture.rowPatches missing")
    {
        let desc = entry.get("desc").and_then(Value::as_str).unwrap_or("");
        let spec = entry.get("patch").expect("rowPatch patch");
        let expected = entry.get("expected").expect("rowPatch expected");
        let op = make_row_patch(&build_row_patch_from_spec(spec)).expect("make_row_patch");
        let actual = serde_json::to_value(&op).unwrap();
        assert_eq!(&actual, expected, "makeRowPatch mismatch [{}]", desc);
    }

    // queryRecordToQueryRow parity — QueryRecord -> QueriesRow field mapping
    // (internal=true vs null, clientAST null for custom, queryArgs passthrough,
    // patchVersion via maybeVersionString incl. the falsy configVersion==0 case).
    for entry in fixture
        .get("queryRows")
        .and_then(Value::as_array)
        .expect("fixture.queryRows missing")
    {
        let desc = entry.get("desc").and_then(Value::as_str).unwrap_or("");
        let spec = entry.get("spec").expect("queryRow spec");
        let expected = entry.get("expected").expect("queryRow expected");
        let qr = build_query_record_from_spec(spec);
        let row = query_record_to_query_row("cg-parity", &qr);
        let actual = serde_json::json!({
            "clientGroupID": row.client_group_id,
            "queryHash": row.query_hash,
            "clientAST": row.client_ast,
            "queryName": row.query_name,
            "queryArgs": row.query_args,
            "patchVersion": row.patch_version,
            "transformationHash": row.transformation_hash,
            "transformationVersion": row.transformation_version,
            "internal": row.internal,
            "deleted": row.deleted,
            "rowSetSignature": row.row_set_signature,
        });
        assert_eq!(
            &actual, expected,
            "queryRecordToQueryRow mismatch [{}]",
            desc
        );
    }

    // mergeRefCounts parity — pins the no-existing zero-retention, negative
    // cancellation, all-zero -> null, and removeHashes-on-existing rules.
    for entry in fixture
        .get("refCountMerges")
        .and_then(Value::as_array)
        .expect("fixture.refCountMerges missing")
    {
        let existing = parse_refcounts(entry.get("existing").expect("existing"));
        let received = parse_refcounts(entry.get("received").expect("received"));
        let remove: Option<HashSet<String>> = entry
            .get("removeHashes")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .map(|s| s.as_str().expect("hash str").to_string())
                    .collect()
            });
        let expected = parse_refcounts(entry.get("expected").expect("expected"));
        let actual = merge_ref_counts(existing.as_ref(), received.as_ref(), remove.as_ref());
        assert_eq!(
            actual, expected,
            "mergeRefCounts mismatch existing={:?} received={:?} rm={:?}",
            existing, received, remove
        );
    }
}
