/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NapiValue {
  kind: string
  boolVal?: boolean
  f64Val?: number
  strVal?: string
  jsonVal?: string
}
export interface NapiRowChange {
  changeType: number
  queryId: string
  table: string
  /**
   * JSON-encoded row key object, e.g. `{"id":"r1"}`.
   * Using String + JSON.parse on the JS side is ~10x faster than
   * HashMap<String, NapiValue> (which creates 5 V8 properties per value).
   */
  rowKey: string
  /** JSON-encoded row object, or null. */
  row?: string
  /** True when this row belongs to a hidden EXISTS/NOT-EXISTS relationship. */
  isHidden: boolean
}
export interface NapiQuerySpec {
  queryId: string
  astJson: string
}
export interface NapiTableSpec {
  table: string
  columns: Record<string, NapiColumnSchema>
  primaryKey: Array<string>
  uniqueKeys?: Array<Array<string>>
  minRowVersion?: string
}
export interface NapiColumnSchema {
  type: string
  optional: boolean
}
/**
 * A synchronous iterator that JS drains in a loop, exactly like TS drains
 * a generator. The iterator holds a boxed closure that produces the next
 * NapiRowChange (or None when done).
 */
export declare class NapiStreamIterator {
  /** Synchronous next — returns the next row, or null when done. */
  next(): NapiRowChange | null
  /** Cancel the iterator — subsequent next() calls return None. */
  cancel(): void
}
export declare class RustIvmEngine {
  constructor()
  /**
   * Initialize ONLY the snapshotter (replica.db connection) so that
   * `read_query` works before `init` is called. This solves the
   * chicken-and-egg: the driver needs to read schema from replica.db
   * (via read_query) to build table specs for `init`, but `init` is
   * what normally creates the snapshotter.
   *
   * Call this FIRST, then `computeZqlSpecs` via `read_query`, then `init`.
   * `init` will skip snapshotter creation if this already did it.
   */
  initSnapshotter(dbPath: string, appId: string): void
  /**
   * Initialize the engine with table schemas and optional SQLite db_path.
   * When db_path is provided, creates TableSource instances backed by SQLite.
   * When no db_path, creates MemorySource instances (test/dev mode).
   * If `init_snapshotter` was called first, the existing snapshotter is
   * reused (its live interrupt registry remains attached).
   */
  init(tables: Array<NapiTableSpec>, dbPath: string | undefined | null, appId: string): void
  /**
   * Add queries and hydrate them on the engine actor, off the JS event loop.
   * Resolves to the full row list.
   */
  addQueriesStreaming(queries: Array<NapiQuerySpec>): Promise<NapiRowChange[]>
  /**
   * Advance to head: Rust derives its own diff from the snapshotter,
   * pushes through pipelines, streams RowChanges.
   * The first row from the iterator is a header (changeType=-1) with
   * version, numChanges, aborted in the row_key field.
   * Advance to head on the engine actor, off the JS event loop.
   * Resolves to `[header, ...rows]` (header changeType=-1; -2 = reset row).
   */
  advanceToHeadStreaming(): Promise<NapiRowChange[]>
  /**
   * Add queries and hydrate them, streaming rows one at a time via `on_row`.
   * Each RowChange is handed to JS as it is produced. A row-credit gate and
   * bounded TSFN queue cap in-flight rows independently of result size.
   */
  addQueriesStreamingRows(queries: Array<NapiQuerySpec>, onRow: (err: Error | null, row: NapiRowChange) => void, streamId: number): Promise<void>
  /**
   * Advance to head, streaming rows one at a time via `on_row`.
   * Header (changeType=-1) is emitted first, change rows in the middle,
   * reset row (changeType=-2) last if the engine reported a reset_reason.
   * Bounded TSFN (max_queue_size=1, Blocking mode) for real backpressure.
   */
  advanceToHeadStreamingRows(onRow: (err: Error | null, row: NapiRowChange) => void, streamId: number): Promise<void>
  removeQuery(queryId: string): void
  /** Scalar-resolved logical AST for public PipelineDriver query metadata. */
  queryTransformedAst(queryId: string): string | null
  /**
   * Sum of successful pipeline hydration times, matching
   * `PipelineDriver.totalHydrationTimeMs()`.
   */
  totalHydrationTimeMs(): number
  /** Store the driver's pause-aware hydration duration for one query. */
  setHydrationTimeMs(queryId: string, hydrationTimeMs: number): boolean
  /**
   * Cancel any in-progress advance or hydrate. **Out-of-band**: flips the
   * shared CancellationToken directly (does NOT queue behind the running job
   * on the actor thread), so it can actually interrupt an advance in flight.
   *
   * N1: ALSO `.interrupt()`s every registered SQLite handle, so a runaway
   * query that the between-rows cancel check never reaches is hard-aborted
   * mid-flight (returns SQLITE_INTERRUPT). Without this, one slow SQLite
   * query wedges the actor thread uninterruptibly until it returns.
   */
  cancel(): void
  /**
   * Grant `permits` streaming-credit back to stream `stream_id` (#3).
   * **Out-of-band**: mutates the shared credit gate directly WITHOUT queueing
   * on the actor thread — which is exactly the point, since the actor is
   * parked inside the stream waiting for these credits. The driver calls this
   * as it drains rows out of its AsyncQueue. A grant tagged to a finished or
   * superseded stream is ignored by the gate, and credit is capped at the
   * window, so a late/duplicate grant can never break the bound.
   */
  grantStreamCredit(streamId: number, permits: number): void
  /**
   * Close stream `stream_id`'s credit gate (#3). **Out-of-band**. The driver
   * calls this when the consumer stops early (generator `return`/`throw`) so
   * the parked producer unparks promptly instead of relying on the fallback
   * poll. Ignored if `stream_id` is not the current stream.
   */
  cancelStream(streamId: number): void
  /** Reset the engine: clear all pipelines and sources. */
  reset(): void
  /**
   * Query planner (`#planAstForRust`): plan `ast_json` (TS-shape) with a cost
   * model backed by the pinned snapshot connection, and return the ordered
   * `flip` decisions as a JSON array (`true`/`false`/`null`). The TS driver
   * walks its own AST in the same order (WHERE pre-order then `related`) and
   * sets `flip` per position. The driver invokes this when the same
   * `enablePlanner` flag used by PipelineDriver is enabled. Returns `[]` if no
   * snapshot exists yet.
   */
  planAst(astJson: string): string
  /**
   * Run a read-only SQL query against the snapshotter's current connection
   * and return the rows as a JSON array of objects. This is the single-owner
   * escape hatch: TS never opens its own replica.db connection; all reads go
   * through the Rust-owned snapshotter connection.
   *
   * `params` is an optional JSON array of bind values, e.g. `["schema", "table"]`.
   * Errors if the snapshotter isn't initialized or the query fails.
   */
  readQuery(sql: string, params?: string | undefined | null): string
  /**
   * Advance the Rust snapshotter to head WITHOUT computing a diff
   * (mirrors TS Snapshotter.advanceWithoutDiff()). Returns the new version.
   *
   * Used by the view-syncer's permission-invalidations path and by the
   * CVR invalidation check. No engine work is triggered.
   */
  advanceWithoutDiff(): string
  /**
   * Read the subscription state (replicaVersion + watermark) from replica.db
   * via the Rust snapshotter's current connection. Returns JSON
   * `{"replicaVersion": "...", "watermark": "..."}`.
   *
   * Mirrors TS `getSubscriptionState()`. The Rust engine owns replica.db,
   * so this is the single-owner read path.
   */
  getSubscriptionState(appId: string): string
  /**
   * Explicit teardown on client-group drop (rust-ivm-driver.destroy()).
   * Frees the engine graph, its SQLite reader connections, and the
   * snapshotter's replica handles NOW rather than waiting for the JS object
   * to be garbage-collected (which is when the actor thread finally exits).
   * Matches the TS PipelineDriver.destroy() contract of prompt resource
   * release. The actor thread itself is cheap (blocked on recv) and still
   * exits on GC; this just avoids holding SQLite fds + IVM memory per dropped
   * CG until the next GC cycle.
   *
   * ASYNC (Promise): blocks until the actor thread confirms teardown.
   * This is the single-owner design — no TS connection races with Rust's
   * because there IS no TS connection. The Rust side drops everything
   * before the Promise resolves.
   */
  destroy(): Promise<void>
  ping(): string
}
